name: Add Hacktoberfest Labels

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Add Hacktoberfest labels to issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            hacktoberfest
            hacktoberfest-accepted
            hacktoberfest2024

      - name: Add Hacktoberfest labels to pull requests
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            hacktoberfest
            hacktoberfest-accepted
            hacktoberfest2024
